#where things are
source:        ./_source
plugins:       ./_source/_plugins
layouts:       ./_source/_layouts
data_source:   ./_source/_data
destination:   ./_deploy

#outputting
timezone:      Europe/Amsterdam
paginate_path: /page:num

